// Synthetic Claude Code transcripts, shaped like Claude Code 2.1.x writes them. Everything in them
// is invented. Used by the tests and by scripts/build-example.mjs; it never touches a real
// Claude folder: write() puts files only under the folder it is given.
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { projectSlug } from "../src/claude.mjs";

// A 1x1 PNG, so image blocks hold real image bytes.
export const PNG_1PX = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";

// A repeatable UUID: the same seed and counter always give the same id.
export function uuid(seed, n = 0) {
  const x = createHash("sha1").update(`${seed}:${n}`).digest("hex");
  return `${x.slice(0, 8)}-${x.slice(8, 12)}-4${x.slice(13, 16)}-${"89ab"[parseInt(x[16], 16) % 4]}${x.slice(17, 20)}-${x.slice(20, 32)}`;
}

export class Transcript {
  // cwd: the project folder the session ran in. start: when it began (ISO). stepMs: time between records.
  constructor({ id, seed, cwd, branch = "main", version = "2.1.286", model = "claude-opus-5-5", start = "2026-10-01T09:00:00.000Z", stepMs = 20000 }) {
    this.seed = seed || id || "session";
    this.id = id || uuid(this.seed, 0);
    this.cwd = cwd;
    this.branch = branch;
    this.version = version;
    this.model = model;
    this.clock = Date.parse(start);
    this.stepMs = stepMs;
    this.records = [];
    this.parent = null;
    this.counter = 1;
    this.msgCounter = 1;
    this.toolCounter = 1;
    this.subagents = []; // { agentId, records }
  }

  now() { const t = new Date(this.clock).toISOString(); this.clock += this.stepMs; return t; }
  skip(ms) { this.clock += ms; return this; }
  nextUuid() { return uuid(this.seed, this.counter++); }

  // A record in the conversation chain: it points at the previous one.
  chain(fields) {
    const rec = {
      parentUuid: this.parent, isSidechain: false, userType: "external", entrypoint: "cli", cwd: this.cwd,
      sessionId: this.id, version: this.version, gitBranch: this.branch, ...fields, uuid: this.nextUuid(), timestamp: this.now(),
    };
    this.records.push(rec);
    this.parent = rec.uuid;
    return rec;
  }
  // A bookkeeping record: not part of the conversation.
  side(fields) { const rec = { sessionId: this.id, ...fields }; this.records.push(rec); return rec; }
  raw(rec) { this.records.push(rec); return rec; }

  // --- the person ---------------------------------------------------------------------------
  user(content, extra = {}) { return this.chain({ type: "user", message: { role: "user", content }, ...extra }); }
  prompt(text) { return this.user(text, { permissionMode: "default" }); }
  promptBlocks(blocks) { return this.user(blocks); }
  image(text = "", media = "image/png", data = PNG_1PX) {
    const blocks = [{ type: "image", source: { type: "base64", media_type: media, data } }];
    if (text) blocks.push({ type: "text", text });
    return this.user(blocks);
  }
  command(name, args = "") {
    const bare = name.replace(/^\//, "");
    return this.user(`<command-message>${bare}</command-message>\n<command-name>/${bare}</command-name>\n<command-args>${args}</command-args>`);
  }
  commandOutput(text) { return this.user(`<local-command-stdout>${text}</local-command-stdout>`); }
  caveat() { return this.user("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>", { isMeta: true }); }
  expansion(text) { return this.user([{ type: "text", text }], { isMeta: true }); }
  bashInput(cmd) { return this.user(`<bash-input>${cmd}</bash-input>`); }
  bashOutput(stdout, stderr = "") { return this.user(`<bash-stdout>${stdout}</bash-stdout><bash-stderr>${stderr}</bash-stderr>`); }
  interrupt(forTool = false) { return this.user([{ type: "text", text: forTool ? "[Request interrupted by user for tool use]" : "[Request interrupted by user]" }]); }
  systemReminder(text) { return this.user([{ type: "text", text: `<system-reminder>${text}</system-reminder>` }], { isMeta: true }); }

  // --- Claude -------------------------------------------------------------------------------
  usage(n = this.msgCounter) {
    return { input_tokens: 100 + n, output_tokens: 40 + n * 2, cache_creation_input_tokens: 200, cache_read_input_tokens: 1000 * n };
  }
  // One assistant message, written as Claude Code does it: one record per content block, all sharing
  // the message id and usage.
  assistant(blocks, { stop = "end_turn", usage, model } = {}) {
    const n = this.msgCounter++;
    const u = usage || this.usage(n);
    return blocks.map((b, i) => this.chain({
      type: "assistant", requestId: `req_${this.seed.slice(0, 6)}${n}`,
      message: { id: `msg_${this.seed.slice(0, 6)}${n}`, type: "message", role: "assistant", model: model || this.model, content: [b], stop_reason: i === blocks.length - 1 ? stop : null, stop_sequence: null, usage: u },
    }));
  }
  say(text, opts) { return this.assistant([{ type: "text", text }], opts); }
  think(text) { return this.assistant([{ type: "thinking", thinking: text, signature: "SIG-" + this.counter }], { stop: null }); }
  // A tool call; returns its id. Pair it with result().
  tool(name, input, preface = []) {
    const id = `toolu_${this.seed.slice(0, 6)}${this.toolCounter++}`;
    this.assistant([...preface, { type: "tool_use", id, name, input }], { stop: "tool_use" });
    return id;
  }
  result(toolId, content, { isError = false, toolUseResult } = {}) {
    const block = { type: "tool_result", tool_use_id: toolId, content };
    if (isError) block.is_error = true;
    const extra = toolUseResult ? { toolUseResult } : {};
    return this.chain({ type: "user", message: { role: "user", content: [block] }, ...extra });
  }
  // A call and its result in one go.
  run(name, input, output, opts) { const id = this.tool(name, input); this.result(id, output, opts); return id; }

  // --- the rest -----------------------------------------------------------------------------
  compact({ trigger = "auto", preTokens = 167000, summary = "The conversation so far: the user is fixing a login bug." } = {}) {
    const before = this.parent;
    this.parent = null;
    this.chain({ type: "system", subtype: "compact_boundary", content: "Conversation compacted", isMeta: false, level: "info", compactMetadata: { trigger, preTokens }, logicalParentUuid: before });
    return this.user([{ type: "text", text: `This session is being continued from a previous conversation that ran out of context. The conversation is summarized below:\n${summary}` }], { isCompactSummary: true, isVisibleInTranscriptOnly: true });
  }
  customTitle(title) { return this.side({ type: "custom-title", customTitle: title }); }
  aiTitle(title) { return this.side({ type: "ai-title", aiTitle: title }); }
  hookContext() { return this.chain({ type: "attachment", attachment: { type: "hook_additional_context", content: ["context from a hook"] } }); }
  // The bookkeeping records Claude Code keeps beside the conversation. A replay ignores all of them.
  bookkeeping() {
    this.side({ type: "queue-operation", operation: "enqueue", timestamp: this.now(), content: "queued" });
    this.side({ type: "file-history-snapshot", messageId: "m1", snapshot: { messageId: "m1", trackedFileBackups: {}, timestamp: this.now() }, isSnapshotUpdate: false });
    this.side({ type: "bridge-session", bridgeSessionId: "bridge-1", lastSequenceNum: 3 });
    this.side({ type: "history-suppression", cause: "restored_owner_mismatch" });
    this.side({ type: "mode", mode: "normal" });
    this.side({ type: "last-prompt", lastPrompt: "x", leafUuid: this.parent });
    this.side({ type: "cost-state", totalCostUSD: 1.5 });
    this.side({ type: "agent-name", agentName: "main" });
    this.side({ type: "pr-link", prNumber: 12 });
    return this;
  }

  // A subagent's own transcript, for a Task or Agent call. Returns the agent id.
  subagent(agentId, prompt, steps) {
    const sub = new Transcript({ seed: `${this.seed}-${agentId}`, id: this.id, cwd: this.cwd, branch: this.branch, version: this.version, model: this.model, start: new Date(this.clock).toISOString(), stepMs: 5000 });
    const mark = (rec) => { rec.isSidechain = true; rec.agentId = agentId; return rec; };
    sub.user(prompt);
    steps(sub);
    sub.records = sub.records.map((r) => (r.uuid ? mark(r) : r));
    this.subagents.push({ agentId, records: sub.records });
    return agentId;
  }

  // Writes <configDir>/projects/<slug>/<id>.jsonl (and the subagent files) and returns where.
  write(configDir, { mtime = true } = {}) {
    const slug = projectSlug(this.cwd);
    const dir = path.join(configDir, "projects", slug);
    fs.mkdirSync(dir, { recursive: true });
    const file = path.join(dir, `${this.id}.jsonl`);
    fs.writeFileSync(file, this.records.map((r) => JSON.stringify(r)).join("\n") + "\n");
    for (const s of this.subagents) {
      const subDir = path.join(dir, this.id, "subagents");
      fs.mkdirSync(subDir, { recursive: true });
      fs.writeFileSync(path.join(subDir, `agent-${s.agentId}.jsonl`), s.records.map((r) => JSON.stringify(r)).join("\n") + "\n");
    }
    if (mtime) { const t = new Date(this.clock); fs.utimesSync(file, t, t); }
    return { id: this.id, file, dir, slug, transcript: this };
  }
}
